### ISSUE TITLE
Meta data json

### ISSUE THREAD

**Issue by rllalloshi** [SpencerWhitehead/NewsVideoDataset#1]
In the repository, I can see only the youtube URLs for the videos but no JSON file for the meta data? Is the meta data publicly available?

Thank you.

**Comment by SpencerWhitehead** [comment]
You are correct that this repo only contains the URLs for the videos. When using youtube-dl command shown here, the `--write-info-json` option will download all the meta-data for you. Then, running the `pack_data.py` script should extract out the meta-data that we used in our work, which will give you the JSON files you're looking for.
