### ISSUE TITLE
Topically related Documents  of the NewsVideoDataset

### ISSUE THREAD

**Issue by WhiteGive-Boy** [SpencerWhitehead/NewsVideoDataset#2]
Can I get the Topically related Documents of the NewsVideoDataset ?  Thanks!

**Comment by SpencerWhitehead** [comment]
Please email me about this for now: srw5 (at) illinois (dot) edu. Thanks!

**Comment by xingye299** [comment]
I also want the  Topically related Documents of the NewsVideoDataset. I have sent you email. Please give me a hand.

**Comment by xingye299** [comment]
> Can I get the Topically related Documents of the NewsVideoDataset ? Thanks!

Have you get the documents? Can you sent me? My email: 736269788@qq.com
